Making theme changes to images, CSS, etc.
OULibraries/oulib_repositorytheme pull request #1
Opened 2017-07-18 15:51 UTC by camp5456

2017-07-18 15:58 UTC, groundedgopher requested changes
We should optimize the images to be at 100kb or less for performance.

2017-07-18 20:31 UTC, c-corbett reviewed
Relevant images have been reduced in size, and obsolete images have been removed. I've also made the contact form removal tweak to the footer.

2017-07-19 15:18 UTC, groundedgopher approved these changes

2017-07-19 15:19 UTC, groundedgopher approved these changes

2017-07-19 15:19 UTC, merged